spring:
application:
name: gateway
server:
port: 8080
ssl:
enabled: true
client-auth: need
key-store: classpath:gateway.jks
key-store-password: qwerty
key-alias: gateway
key-store-type: JKS
key-store-provider: SUN
trust-store: classpath:gateway.jks
trust-store-password: qwerty
trust-store-type: JKS
